services:
#    warden.drupal.module:
#        class: Deeson\WardenDrupalBundle\Managers\ModuleManager
#        arguments: ['@doctrine_mongodb', '@monolog.logger']

    warden.drupal.site:
        class: Deeson\WardenDrupalBundle\Services\DrupalSiteService
        arguments: ['@warden.drupal.module_manager', '@warden.site_connection', '@monolog.logger', '@event_dispatcher']
        tags:
            - { name: kernel.event_listener, event: warden.site.update, method: onWardenSiteUpdate }
            - { name: kernel.event_listener, event: warden.site.refresh, method: onWardenSiteRefresh }
            - { name: kernel.event_listener, event: warden.site.show, method: onWardenSiteShow }
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 100 }

    warden.drupal.module_service:
        class: Deeson\WardenDrupalBundle\Services\DrupalModuleService
        arguments: ['@warden.drupal.module_manager', '@warden.site_manager', '@monolog.logger']
        tags:
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 30 }

    warden.drupal.module_version:
        class: Deeson\WardenDrupalBundle\Services\DrupalUpdateRequestService
        arguments: ['@warden.http_client', '@warden.site_manager', '@warden.drupal.module_manager', '@monolog.logger']
        tags:
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 60 }


